development:
  base_url: localhost:3000
  secret_key_base: 8978b6a9ee6976507fe9f22e8833613f452c091c54625950a66f2adcf1b6d9a4e76438f5df6b28a3552c79fed632d9bec0d7ea655527dba7660ae5da7b82eeb7
  branch_client_key: key_live_inIaIbO3p1hjZaohK69T1maeEzoLfrc7
  branch_client_secret: secret_live_pxeEboOXslPwk1FM0WNVY5uDXeLSOOG6
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  host: http://localhost:3000
  one_signal_app_id: 5329c542-8eea-4613-8946-8829bb853e8b
  one_signal_api_key: Y2E0ZjE0YmMtYjA3MS00NzE1LTkxYTgtYmYzYWI4ZjQzNGUz

test:
  secret_key_base: 25c4c6109264652f2b9613e53201bc93954358014efa1f0bf389b0560b1c84b2a82a77217344846772719d5ed0c0702ade99ee76ab570e4a79887d654c7ffccd
  base_url: localhost:3000
  branch_client_key: key_live_inIaIbO3p1hjZaohK69T1maeEzoLfrc7
  branch_client_secret: secret_live_pxeEboOXslPwk1FM0WNVY5uDXeLSOOG6
  sendgrid_username:
  sendgrid_password:
  one_signal_app_id: 5329c542-8eea-4613-8946-8829bb853e8b
  one_signal_api_key: Y2E0ZjE0YmMtYjA3MS00NzE1LTkxYTgtYmYzYWI4ZjQzNGUz

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  base_url: <%= ENV["BASE_URL"] %>
  branch_client_key: key_live_inIaIbO3p1hjZaohK69T1maeEzoLfrc7
  branch_client_secret: secret_live_pxeEboOXslPwk1FM0WNVY5uDXeLSOOG6
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  host: <%= ENV['API_HOST'] %>
  one_signal_app_id: 5329c542-8eea-4613-8946-8829bb853e8b
  one_signal_api_key: Y2E0ZjE0YmMtYjA3MS00NzE1LTkxYTgtYmYzYWI4ZjQzNGUz
